<?xml version="1.0"?>
<package format="3">
  <name>rplidar_ros</name>
  <version>2.1.4</version>
  <description>
    The rplidar ros package, support rplidar A1/A2/A3/S1/S2/S3/T1
  </description>

  <maintainer email="deyou.wang@slamtec.com">Wang DeYou</maintainer>
  <author email="ros@slamtec.com">Slamtec ROS Maintainer</author>
  <license>BSD</license>

  <buildtool_depend>ament_cmake_auto</buildtool_depend>
  <buildtool_depend>ament_cmake_ros</buildtool_depend>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <depend>rclcpp</depend>
  <depend>std_srvs</depend>
  <depend>sensor_msgs</depend>
  <depend>rclcpp_components</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
